name: geo_fin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  toastification: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/src/core/generated/
  line_length: 150

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
